[platformio]
default_envs = mega2_controller

[env]
platform = atmelavr
framework = arduino
monitor_speed = 115200
build_flags =
  -Wall

[env:mega2_controller]
board = megaatmega2560
upload_port = COM10
build_flags =
  ${env.build_flags}
  -DROLE_MEGA2_CONTROLLER
  -DNODE_ID=200

[env:mega1_relay]
board = megaatmega2560
upload_port = COM9
build_flags =
  ${env.build_flags}
  -DROLE_MEGA1_RELAY
  -DNODE_ID=100

[env:nano_switch]
board = nanoatmega328new
upload_port = COM11
build_flags =
  ${env.build_flags}
  -DROLE_NANO_SWITCH
  -DNEOSWSERIAL_EXTERNAL_PCINT

[env:uno1_host]
board = uno
upload_port = COM8
build_flags =
  ${env.build_flags}
  -DROLE_UNO_HOST
  -DNODE_ID=100

[env:uno2_host]
board = uno
upload_port = COM7
build_flags =
  ${env.build_flags}
  -DROLE_UNO_HOST
  -DNODE_ID=200
